### ISSUE TITLE
socket issue

### ISSUE THREAD

**Issue by ehiverson** [ehiverson/DS1054Z_screen_capture#2]
There is a problem similar to this one: 
https://stackoverflow.com/questions/33003498/typeerror-a-bytes-like-object-is-required-not-str

**Comment by ehiverson** [comment]
Resolved using encode() and decode() where needed.

**Comment by spiff72** [comment]
Sorry for inquiring here, but is there a place I can see the corrections needed to these files to allow use with python 3?  I have modified the code on my end to address some of the other issues with the pip import and print statements and error handling, but I can't figure out what to do to fix these byte/string errors.

Thanks!

**Comment by spiff72** [comment]
Disregard.  I realized that you DO have encode/decode stuff in the files (I downloaded your repo).  However, I am still getting a LOT of errors, so I will just use python 2 (which works fine with some minor fixes).

It would be great if this could get ported properly to Python3, though!

Thanks!
